// Code generated from the site's data/quotes/*.ts corpus. DO NOT EDIT BY HAND.

package club

// Quote is one entry of the club's quote corpus.
type Quote struct {
	Text   string
	Author string
}

// Quotes is the deduplicated corpus in batch order: simplicity, correctness,
// craft, foss, systems, mindset — matching data/quotes/index.ts on the site.
var Quotes = []Quote{
	{Text: "Simplicity is prerequisite for reliability.", Author: "Edsger W. Dijkstra"},
	{Text: "There are two ways of constructing a software design: one way is to make it so simple that there are obviously no deficiencies, and the other way is to make it so complicated that there are no obvious deficiencies.", Author: "C. A. R. Hoare"},
	{Text: "Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away.", Author: "Antoine de Saint-Exupery"},
	{Text: "Simple things should be simple, complex things should be possible.", Author: "Alan Kay"},
	{Text: "Write programs that do one thing and do it well. Write programs to work together. Write programs to handle text streams, because that is a universal interface.", Author: "Doug McIlroy"},
	{Text: "Controlling complexity is the essence of computer programming.", Author: "Brian Kernighan"},
	{Text: "Debugging is twice as hard as writing the code in the first place. Therefore, if you write the code as cleverly as possible, you are, by definition, not smart enough to debug it.", Author: "Brian Kernighan"},
	{Text: "Data dominates. If you've chosen the right data structures and organized things well, the algorithms will almost always be self-evident.", Author: "Rob Pike"},
	{Text: "Fancy algorithms are slow when n is small, and n is usually small.", Author: "Rob Pike"},
	{Text: "Fancy algorithms are buggier than simple ones, and they're much harder to implement. Use simple algorithms as well as simple data structures.", Author: "Rob Pike"},
	{Text: "Simplicity is the art of hiding complexity.", Author: "Rob Pike"},
	{Text: "Clear is better than clever.", Author: "Rob Pike"},
	{Text: "A little copying is better than a little dependency.", Author: "Rob Pike"},
	{Text: "The bigger the interface, the weaker the abstraction.", Author: "Rob Pike"},
	{Text: "One of my most productive days was throwing away 1,000 lines of code.", Author: "Ken Thompson"},
	{Text: "UNIX is basically a simple operating system, but you have to be a genius to understand the simplicity.", Author: "Dennis Ritchie"},
	{Text: "The only way to write complex software that won't fall on its face is to hold its global complexity down: to build it out of simple parts connected by well-defined interfaces.", Author: "Eric S. Raymond"},
	{Text: "Simplicity is a great virtue but it requires hard work to achieve it and education to appreciate it. And to make matters worse: complexity sells better.", Author: "Edsger W. Dijkstra"},
	{Text: "The purpose of abstraction is not to be vague, but to create a new semantic level in which one can be absolutely precise.", Author: "Edsger W. Dijkstra"},
	{Text: "In programming, simplicity and clarity - in short, what mathematicians call elegance - are not a dispensable luxury, but a crucial matter that decides between success and failure.", Author: "Edsger W. Dijkstra"},
	{Text: "Inside every large program is a small program struggling to get out.", Author: "C. A. R. Hoare"},
	{Text: "Fools ignore complexity. Pragmatists suffer it. Some can avoid it. Geniuses remove it.", Author: "Alan Perlis"},
	{Text: "Simplicity does not precede complexity, but follows it.", Author: "Alan Perlis"},
	{Text: "It is better to have 100 functions operate on one data structure than 10 functions on 10 data structures.", Author: "Alan Perlis"},
	{Text: "A programming language is low level when its programs require attention to the irrelevant.", Author: "Alan Perlis"},
	{Text: "Software is getting slower more rapidly than hardware becomes faster.", Author: "Niklaus Wirth"},
	{Text: "The most important decisions in language design concern what is to be left out.", Author: "Niklaus Wirth"},
	{Text: "Simplicity is hard work. But there's a huge payoff: the person who has a genuinely simpler system is going to be able to effect the greatest change with the least work.", Author: "Rich Hickey"},
	{Text: "Programmers know the benefits of everything and the tradeoffs of nothing.", Author: "Rich Hickey"},
	{Text: "If you want everything to be familiar, you will never learn anything new.", Author: "Rich Hickey"},
	{Text: "Simplicity is a choice.", Author: "Rich Hickey"},
	{Text: "Simplicity before generality, use before reuse.", Author: "Kevlin Henney"},
	{Text: "All problems in computer science can be solved by another level of indirection.", Author: "David Wheeler"},
	{Text: "...except for the problem of too many layers of indirection.", Author: "Kevlin Henney"},
	{Text: "The greatest limitation in writing software is our ability to understand the systems we are creating.", Author: "John Ousterhout"},
	{Text: "Complexity is incremental: you have to sweat the small stuff.", Author: "John Ousterhout"},
	{Text: "The best modules are those that provide powerful functionality yet have simple interfaces.", Author: "John Ousterhout"},
	{Text: "Working code isn't enough.", Author: "John Ousterhout"},
	{Text: "Most software today is very much like an Egyptian pyramid with millions of bricks piled on top of each other, with no structural integrity, but just done by brute force and thousands of slaves.", Author: "Alan Kay"},
	{Text: "All non-trivial abstractions, to some degree, are leaky.", Author: "Joel Spolsky"},
	{Text: "Simple can be harder than complex: you have to work hard to get your thinking clean to make it simple. But it's worth it in the end because once you get there, you can move mountains.", Author: "Steve Jobs"},
	{Text: "Bad programmers worry about the code. Good programmers worry about data structures and their relationships.", Author: "Linus Torvalds"},
	{Text: "Sometimes you can see a problem in a different way and rewrite it so that a special case goes away and becomes the normal case. That's good taste.", Author: "Linus Torvalds"},
	{Text: "Show me your flowcharts and conceal your tables, and I shall continue to be mystified. Show me your tables, and I won't usually need your flowcharts; they'll be obvious.", Author: "Fred Brooks"},
	{Text: "Conceptual integrity is the most important consideration in system design.", Author: "Fred Brooks"},
	{Text: "I have always wished for my computer to be as easy to use as my telephone; my wish has come true because I can no longer figure out how to use my telephone.", Author: "Bjarne Stroustrup"},
	{Text: "Complexity kills. It sucks the life out of developers, it makes products difficult to plan, build and test.", Author: "Ray Ozzie"},
	{Text: "Every program attempts to expand until it can read mail. Those programs which cannot so expand are replaced by ones which can.", Author: "Jamie Zawinski"},
	{Text: "For each desired change, make the change easy (warning: this may be hard), then make the easy change.", Author: "Kent Beck"},
	{Text: "Any fool can write code that a computer can understand. Good programmers write code that humans can understand.", Author: "Martin Fowler"},
	{Text: "Programs must be written for people to read, and only incidentally for machines to execute.", Author: "Harold Abelson"},
	{Text: "We should have some ways of coupling programs like garden hose - screw in another segment when it becomes necessary to massage data in another way.", Author: "Doug McIlroy"},
	{Text: "Good design is as little design as possible.", Author: "Dieter Rams"},
	{Text: "The cheapest, fastest, and most reliable components are those that aren't there.", Author: "Gordon Bell"},
	{Text: "Small is beautiful.", Author: "Unix proverb"},
	{Text: "Keep it simple, stupid.", Author: "Kelly Johnson"},
	{Text: "Duplication is far cheaper than the wrong abstraction.", Author: "Sandi Metz"},
	{Text: "The best code is no code at all.", Author: "Jeff Atwood"},
	{Text: "Program testing can be used to show the presence of bugs, but never to show their absence!", Author: "Edsger W. Dijkstra"},
	{Text: "Beware of bugs in the above code; I have only proved it correct, not tried it.", Author: "Donald Knuth"},
	{Text: "I call it my billion-dollar mistake. It was the invention of the null reference in 1965.", Author: "C.A.R. Hoare"},
	{Text: "A distributed system is one in which the failure of a computer you didn't even know existed can render your own computer unusable.", Author: "Leslie Lamport"},
	{Text: "Writing is nature's way of letting you know how sloppy your thinking is.", Author: "Leslie Lamport"},
	{Text: "If you're thinking without writing, you only think you're thinking.", Author: "Leslie Lamport"},
	{Text: "Legacy code is simply code without tests.", Author: "Michael Feathers"},
	{Text: "Whenever you are tempted to type something into a print statement or a debugger expression, write it as a test instead.", Author: "Martin Fowler"},
	{Text: "I'm not a great programmer; I'm just a good programmer with great habits.", Author: "Kent Beck"},
	{Text: "Make it work, make it right, make it fast.", Author: "Kent Beck"},
	{Text: "I get paid for code that works, not for tests, so my philosophy is to test as little as possible to reach a given level of confidence.", Author: "Kent Beck"},
	{Text: "Test until fear turns to boredom.", Author: "Kent Beck"},
	{Text: "The most effective debugging tool is still careful thought, coupled with judiciously placed print statements.", Author: "Brian Kernighan"},
	{Text: "It works on my machine.", Author: "Programming proverb"},
	{Text: "Some people, when confronted with a problem, think \"I know, I'll use regular expressions.\" Now they have two problems.", Author: "Jamie Zawinski"},
	{Text: "There are only two hard things in Computer Science: cache invalidation and naming things.", Author: "Phil Karlton"},
	{Text: "There are only two hard problems in distributed systems: 2. Exactly-once delivery 1. Guaranteed order of messages 2. Exactly-once delivery.", Author: "Mathias Verraes"},
	{Text: "If debugging is the process of removing bugs, then programming must be the process of putting them in.", Author: "Edsger W. Dijkstra"},
	{Text: "The question of whether a computer can think is no more interesting than the question of whether a submarine can swim.", Author: "Edsger W. Dijkstra"},
	{Text: "It is easier to ask forgiveness than it is to get permission.", Author: "Grace Hopper"},
	{Text: "The most dangerous phrase in the language is, \"We've always done it this way.\"", Author: "Grace Hopper"},
	{Text: "From then on, when anything went wrong with a computer, we said it had bugs in it.", Author: "Grace Hopper"},
	{Text: "If builders built buildings the way programmers wrote programs, then the first woodpecker that came along would destroy civilization.", Author: "Gerald Weinberg"},
	{Text: "Not all problems have a technological answer, but when they do, that is the more lasting solution.", Author: "Gerald Weinberg"},
	{Text: "No matter what the problem is, it's always a people problem.", Author: "Gerald Weinberg"},
	{Text: "Bugs are never found by the test you expected to find them.", Author: "Programming proverb"},
	{Text: "The sooner you start to code, the longer the program will take.", Author: "Roy Carlson"},
	{Text: "Incorrect documentation is often worse than no documentation.", Author: "Bertrand Meyer"},
	{Text: "Bubbles don't crash.", Author: "Bertrand Meyer"},
	{Text: "Correctness is clearly the prime quality. If a system does not do what it is supposed to do, then everything else about it matters little.", Author: "Bertrand Meyer"},
	{Text: "The problem with quick and dirty is that dirty remains long after quick has been forgotten.", Author: "Steve McConnell"},
	{Text: "Testing by itself does not improve software quality. Test results are an indicator of quality, but in and of themselves, they don't improve it.", Author: "Steve McConnell"},
	{Text: "Trying to improve software quality by increasing the amount of testing is like trying to lose weight by weighing yourself more often.", Author: "Steve McConnell"},
	{Text: "Anything that can go wrong will go wrong.", Author: "Murphy's Law"},
	{Text: "If it ain't broke, you're not trying hard enough.", Author: "Anonymous"},
	{Text: "A bug in the hand is worth two in the box.", Author: "Programming proverb"},
	{Text: "Given enough eyeballs, all bugs are shallow.", Author: "Eric S. Raymond"},
	{Text: "Every program has at least one bug and can be shortened by at least one instruction, from which, by induction, one can deduce that every program can be reduced to one instruction which doesn't work.", Author: "Programming proverb"},
	{Text: "Weeks of coding can save you hours of planning.", Author: "Anonymous"},
	{Text: "The first 90 percent of the code accounts for the first 90 percent of the development time. The remaining 10 percent of the code accounts for the other 90 percent of the development time.", Author: "Tom Cargill"},
	{Text: "Don't be afraid of testing code; being afraid of not testing it is the right attitude.", Author: "Anonymous"},
	{Text: "If you don't have tests, you have no idea whether your code works. You only have hope.", Author: "Anonymous"},
	{Text: "In theory, there is no difference between theory and practice. In practice, there is.", Author: "Anonymous"},
	{Text: "Learn at least a half dozen programming languages. Include one that emphasizes class abstractions, one that emphasizes functional abstraction, one that supports syntactic abstraction, one with declarative specifications, and one that emphasizes parallelism.", Author: "Peter Norvig"},
	{Text: "Programming is not about typing, it's about thinking.", Author: "Rich Hickey"},
	{Text: "The best way to get a project done faster is to start sooner.", Author: "Jim Highsmith"},
	{Text: "Deleted code is debugged code.", Author: "Jeff Sickel"},
	{Text: "Beware of the person who says, \"It works, but I don't know why.\"", Author: "Programming proverb"},
	{Text: "The ratio of time spent reading versus writing is well over 10 to 1. We are constantly reading old code as part of the effort to write new code.", Author: "Robert C. Martin"},
	{Text: "Code is read much more often than it is written.", Author: "Guido van Rossum"},
	{Text: "Programming is the art of telling another human being what one wants the computer to do.", Author: "Donald Knuth"},
	{Text: "Instead of imagining that our main task is to instruct a computer what to do, let us concentrate rather on explaining to human beings what we want a computer to do.", Author: "Donald Knuth"},
	{Text: "Optimism is an occupational hazard of programming; feedback is the treatment.", Author: "Kent Beck"},
	{Text: "Shipping first time code is like going into debt. A little debt speeds development so long as it is paid back promptly with a rewrite.", Author: "Ward Cunningham"},
	{Text: "Beautiful is better than ugly.", Author: "Tim Peters"},
	{Text: "Explicit is better than implicit.", Author: "Tim Peters"},
	{Text: "Simple is better than complex.", Author: "Tim Peters"},
	{Text: "Complex is better than complicated.", Author: "Tim Peters"},
	{Text: "Flat is better than nested.", Author: "Tim Peters"},
	{Text: "Sparse is better than dense.", Author: "Tim Peters"},
	{Text: "Readability counts.", Author: "Tim Peters"},
	{Text: "Special cases aren't special enough to break the rules.", Author: "Tim Peters"},
	{Text: "If the implementation is hard to explain, it's a bad idea.", Author: "Tim Peters"},
	{Text: "There should be one-- and preferably only one --obvious way to do it.", Author: "Tim Peters"},
	{Text: "We will encourage you to develop the three great virtues of a programmer: laziness, impatience, and hubris.", Author: "Larry Wall"},
	{Text: "It's harder to read code than to write it.", Author: "Joel Spolsky"},
	{Text: "The idea that new code is better than old is patently absurd. Old code has been used. It has been tested.", Author: "Joel Spolsky"},
	{Text: "Good software, like wine, takes time.", Author: "Joel Spolsky"},
	{Text: "Good code is its own best documentation. As you're about to add a comment, ask yourself, 'How can I improve the code so this comment isn't needed?'", Author: "Steve McConnell"},
	{Text: "Programming is not like being in the CIA; you don't get credit for being sneaky.", Author: "Steve McConnell"},
	{Text: "Every piece of knowledge must have a single, unambiguous, authoritative representation within a system.", Author: "Andy Hunt and Dave Thomas"},
	{Text: "Care about your craft. Why spend your life developing software unless you care about doing it well?", Author: "Andy Hunt and Dave Thomas"},
	{Text: "Design is the art of arranging code to work today, and to be changeable forever.", Author: "Sandi Metz"},
	{Text: "Whenever I have to think to understand what the code is doing, I ask myself if I can refactor the code to make that understanding more immediately apparent.", Author: "Martin Fowler"},
	{Text: "I like my code to be elegant and efficient. The logic should be straightforward to make it hard for bugs to hide.", Author: "Bjarne Stroustrup"},
	{Text: "If a feature is sometimes useful and sometimes dangerous and if there is a better option then always use the better option.", Author: "Douglas Crockford"},
	{Text: "If you're willing to restrict the flexibility of your approach, you can almost always do something better.", Author: "John Carmack"},
	{Text: "The cost of adding a feature isn't just the time it takes to code it. The cost also includes the addition of an obstacle to future expansion.", Author: "John Carmack"},
	{Text: "Talk is cheap. Show me the code.", Author: "Linus Torvalds"},
	{Text: "It is easier to write an incorrect program than understand a correct one.", Author: "Alan Perlis"},
	{Text: "Syntactic sugar causes cancer of the semicolon.", Author: "Alan Perlis"},
	{Text: "Don't comment bad code - rewrite it.", Author: "Brian Kernighan and P.J. Plauger"},
	{Text: "Clean code is simple and direct. Clean code reads like well-written prose.", Author: "Grady Booch"},
	{Text: "Clean code always looks like it was written by someone who cares.", Author: "Michael Feathers"},
	{Text: "Code never lies, comments sometimes do.", Author: "Ron Jeffries"},
	{Text: "Code should be written to minimize the time it would take for someone else to understand it.", Author: "Dustin Boswell and Trevor Foucher"},
	{Text: "Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live.", Author: "John Woods"},
	{Text: "Free software is a matter of liberty, not price. Think of \"free\" as in \"free speech,\" not as in \"free beer.\"", Author: "Richard Stallman"},
	{Text: "Sharing of software is as old as computers, just as sharing of recipes is as old as cooking.", Author: "Richard Stallman"},
	{Text: "If programmers deserve to be rewarded for creating innovative programs, they also deserve to be punished if they restrict the use of these programs.", Author: "Richard Stallman"},
	{Text: "Value your freedom or you will lose it, teaches history. \"Don't bother us with politics,\" respond those who don't want to learn.", Author: "Richard Stallman"},
	{Text: "I'm doing a (free) operating system (just a hobby, won't be big and professional like gnu) for 386(486) AT clones.", Author: "Linus Torvalds"},
	{Text: "Software is like sex: it's better when it's free.", Author: "Linus Torvalds"},
	{Text: "Most good programmers do programming not because they expect to get paid or get adulation by the public, but because it is fun to program.", Author: "Linus Torvalds"},
	{Text: "Every good work of software starts by scratching a developer's personal itch.", Author: "Eric S. Raymond"},
	{Text: "Release early. Release often. And listen to your customers.", Author: "Eric S. Raymond"},
	{Text: "Good programmers know what to write. Great ones know what to rewrite (and reuse).", Author: "Eric S. Raymond"},
	{Text: "Treating your users as co-developers is your least-hassle route to rapid code improvement and effective debugging.", Author: "Eric S. Raymond"},
	{Text: "The next best thing to having good ideas is recognizing good ideas from your users. Sometimes the latter is better.", Author: "Eric S. Raymond"},
	{Text: "Smart data structures and dumb code works a lot better than the other way around.", Author: "Eric S. Raymond"},
	{Text: "When in doubt, use brute force.", Author: "Ken Thompson"},
	{Text: "You can't trust code that you did not totally create yourself.", Author: "Ken Thompson"},
	{Text: "The only way to learn a new programming language is by writing programs in it.", Author: "Dennis Ritchie"},
	{Text: "The real hero of programming is the one who writes negative code.", Author: "Doug McIlroy"},
	{Text: "Don't communicate by sharing memory; share memory by communicating.", Author: "Rob Pike"},
	{Text: "No matter who you are, most of the smartest people work for someone else.", Author: "Bill Joy"},
	{Text: "The Web as I envisaged it, we have not seen it yet. The future is still so much bigger than the past.", Author: "Tim Berners-Lee"},
	{Text: "This is for everyone.", Author: "Tim Berners-Lee"},
	{Text: "Information is power. But like all power, there are those who want to keep it for themselves.", Author: "Aaron Swartz"},
	{Text: "Be curious. Read widely. Try new things. What people call intelligence just boils down to curiosity.", Author: "Aaron Swartz"},
	{Text: "Sharing isn't immoral; it's a moral imperative. Only those blinded by greed would refuse to let a friend make a copy.", Author: "Aaron Swartz"},
	{Text: "With software, either the users control the program or the program controls the users.", Author: "Richard Stallman"},
	{Text: "The Open Source Definition is a bill of rights for the computer user.", Author: "Bruce Perens"},
	{Text: "There's more than one way to do it.", Author: "Larry Wall"},
	{Text: "Easy things should be easy, and hard things should be possible.", Author: "Larry Wall"},
	{Text: "Open source is a development methodology; free software is a social movement.", Author: "Richard Stallman"},
	{Text: "Open source has the potential to give people the tools to fix things themselves, and that's incredibly empowering.", Author: "Brian Behlendorf"},
	{Text: "Information wants to be free.", Author: "Stewart Brand"},
	{Text: "Access to computers -- and anything which might teach you something about the way the world works -- should be unlimited and total.", Author: "Steven Levy (The Hacker Ethic)"},
	{Text: "Hackers should be judged by their hacking, not bogus criteria such as degrees, age, race, or position.", Author: "Steven Levy (The Hacker Ethic)"},
	{Text: "The best way to predict the future is to invent it.", Author: "Alan Kay"},
	{Text: "The value of a network grows as the square of the number of its users.", Author: "Bob Metcalfe (Metcalfe's Law)"},
	{Text: "It Has To Work.", Author: "RFC 1925"},
	{Text: "With sufficient thrust, pigs fly just fine. However, this is not necessarily a good idea.", Author: "RFC 1925"},
	{Text: "It is always possible to add another level of indirection.", Author: "RFC 1925"},
	{Text: "Be conservative in what you do, be liberal in what you accept from others.", Author: "Jon Postel"},
	{Text: "We reject: kings, presidents and voting. We believe in: rough consensus and running code.", Author: "David D. Clark (IETF credo)"},
	{Text: "The Internet is for everyone -- but it won't be if it isn't affordable by all.", Author: "Vint Cerf"},
	{Text: "The Analytical Engine weaves algebraical patterns just as the Jacquard loom weaves flowers and leaves.", Author: "Ada Lovelace"},
	{Text: "We can only see a short distance ahead, but we can see plenty there that needs to be done.", Author: "Alan Turing"},
	{Text: "Those who do not understand Unix are condemned to reinvent it, poorly.", Author: "Henry Spencer"},
	{Text: "Patches welcome.", Author: "Hacker proverb"},
	{Text: "Adding manpower to a late software project makes it later.", Author: "Fred Brooks"},
	{Text: "Plan to throw one away; you will, anyhow.", Author: "Fred Brooks"},
	{Text: "The bearing of a child takes nine months, no matter how many women are assigned.", Author: "Fred Brooks"},
	{Text: "There is no single development, in either technology or management technique, which by itself promises even one order-of-magnitude improvement in productivity, reliability, or simplicity.", Author: "Fred Brooks"},
	{Text: "We should forget about small efficiencies, say about 97% of the time: premature optimization is the root of all evil.", Author: "Donald Knuth"},
	{Text: "You can't tell where a program is going to spend its time. Bottlenecks occur in surprising places, so don't put in a speed hack until you've proven that's where the bottleneck is.", Author: "Rob Pike"},
	{Text: "Measure. Don't tune for speed until you've measured, and even then don't unless one part of the code overwhelms the rest.", Author: "Rob Pike"},
	{Text: "Keep it simple. Don't generalize; generalizations are generally wrong.", Author: "Butler Lampson"},
	{Text: "Handle normal and worst cases separately. The normal case must be fast; the worst case must make some progress.", Author: "Butler Lampson"},
	{Text: "Make it fast, rather than general or powerful.", Author: "Butler Lampson"},
	{Text: "Tape is dead, disk is tape, flash is disk, RAM locality is king.", Author: "Jim Gray"},
	{Text: "If for each object o1 of type S there is an object o2 of type T such that programs defined in terms of T behave the same when o1 is substituted for o2, then S is a subtype of T.", Author: "Barbara Liskov"},
	{Text: "The effort expended on achieving high parallel processing rates is wasted unless it is accompanied by achievements in sequential processing rates of very nearly the same magnitude.", Author: "Gene Amdahl"},
	{Text: "Anyone can build a fast CPU. The trick is to build a fast system.", Author: "Seymour Cray"},
	{Text: "If you were plowing a field, which would you rather use: two strong oxen or 1024 chickens?", Author: "Seymour Cray"},
	{Text: "C is quirky, flawed, and an enormous success.", Author: "Dennis Ritchie"},
	{Text: "Fallacy #1 of distributed computing: the network is reliable.", Author: "Peter Deutsch"},
	{Text: "Fallacy #2 of distributed computing: latency is zero.", Author: "Peter Deutsch"},
	{Text: "Fallacy #3 of distributed computing: bandwidth is infinite.", Author: "Peter Deutsch"},
	{Text: "Fallacy #4 of distributed computing: the network is secure.", Author: "Peter Deutsch"},
	{Text: "Fallacy #5 of distributed computing: topology doesn't change.", Author: "Peter Deutsch"},
	{Text: "Fallacy #6 of distributed computing: there is one administrator.", Author: "Peter Deutsch"},
	{Text: "Fallacy #7 of distributed computing: transport cost is zero.", Author: "Peter Deutsch"},
	{Text: "Fallacy #8 of distributed computing: the network is homogeneous.", Author: "Peter Deutsch"},
	{Text: "Organizations which design systems are constrained to produce designs which are copies of the communication structures of these organizations.", Author: "Melvin Conway"},
	{Text: "A complex system that works is invariably found to have evolved from a simple system that worked. A complex system designed from scratch never works.", Author: "John Gall"},
	{Text: "With a sufficient number of users of an API, it does not matter what you promise in the contract: all observable behaviors of your system will be depended on by somebody.", Author: "Hyrum Wright"},
	{Text: "Everything fails, all the time.", Author: "Werner Vogels"},
	{Text: "Make it work, then make it beautiful, then if you really, really have to, make it fast.", Author: "Joe Armstrong"},
	{Text: "You wanted a banana but what you got was a gorilla holding the banana and the entire jungle.", Author: "Joe Armstrong"},
	{Text: "Let it crash.", Author: "Joe Armstrong"},
	{Text: "Design for ~10X growth, but plan to rewrite before ~100X.", Author: "Jeff Dean"},
	{Text: "\"One size fits all\" is an idea whose time has come and gone.", Author: "Michael Stonebraker"},
	{Text: "The unavoidable price of reliability is simplicity.", Author: "C.A.R. Hoare"},
	{Text: "Optimization hinders evolution.", Author: "Alan Perlis"},
	{Text: "Every program has (at least) two purposes: the one for which it was written and another for which it wasn't.", Author: "Alan Perlis"},
	{Text: "Never underestimate the bandwidth of a station wagon full of tapes hurtling down the highway.", Author: "Andrew Tanenbaum"},
	{Text: "Rules of Optimization: Rule 1: Don't do it. Rule 2 (for experts only): Don't do it yet.", Author: "Michael A. Jackson"},
	{Text: "The greatest performance improvement of all is when a system goes from not-working to working.", Author: "John Ousterhout"},
	{Text: "Real artists ship.", Author: "Steve Jobs"},
	{Text: "Done is better than perfect.", Author: "Programming proverb"},
	{Text: "Hackers and painters have a lot in common. Both are makers.", Author: "Paul Graham"},
	{Text: "A programming language is for thinking about programs, not for expressing programs you've already thought of.", Author: "Paul Graham"},
	{Text: "Write code that is easy to delete, not easy to extend.", Author: "Programming proverb"},
	{Text: "The competent programmer is fully aware of the strictly limited size of his own skull; therefore he approaches the programming task in full humility.", Author: "Edsger W. Dijkstra"},
	{Text: "A ship in port is safe, but that's not what ships are built for.", Author: "Grace Hopper"},
	{Text: "What I cannot create, I do not understand.", Author: "Richard Feynman"},
	{Text: "The first principle is that you must not fool yourself, and you are the easiest person to fool.", Author: "Richard Feynman"},
	{Text: "You can't think seriously about thinking without thinking about thinking about something.", Author: "Seymour Papert"},
	{Text: "Measuring programming progress by lines of code is like measuring aircraft building progress by weight.", Author: "Bill Gates"},
	{Text: "There are only two kinds of languages: the ones people complain about and the ones nobody uses.", Author: "Bjarne Stroustrup"},
	{Text: "If you think like a computer, writing C actually makes sense.", Author: "Linus Torvalds"},
	{Text: "Truth can only be found in one place: the code.", Author: "Robert C. Martin"},
	{Text: "The only way to go fast is to go well.", Author: "Robert C. Martin"},
	{Text: "Don't live with broken windows. Fix bad designs, wrong decisions, and poor code when you see them.", Author: "Andy Hunt & Dave Thomas"},
	{Text: "Invest regularly in your knowledge portfolio. Make learning a habit.", Author: "Andy Hunt & Dave Thomas"},
	{Text: "Be a catalyst for change. You can't force change on people. Show them how the future might be and help them participate in creating it.", Author: "Andy Hunt & Dave Thomas"},
	{Text: "Don't assume it, prove it. Prove your assumptions in the actual environment, with real data and boundary conditions.", Author: "Andy Hunt & Dave Thomas"},
	{Text: "Use tracer bullets to find the target. Get something working end to end first, then refine.", Author: "Andy Hunt & Dave Thomas"},
	{Text: "A language that doesn't affect the way you think about programming is not worth knowing.", Author: "Alan Perlis"},
	{Text: "There are two ways to write error-free programs; only the third one works.", Author: "Alan Perlis"},
	{Text: "It always takes longer than you expect, even when you take into account Hofstadter's Law.", Author: "Douglas Hofstadter"},
	{Text: "A good programmer is someone who always looks both ways before crossing a one-way street.", Author: "Doug Linder"},
	{Text: "Programming today is a race between software engineers striving to build bigger and better idiot-proof programs, and the Universe trying to produce bigger and better idiots. So far, the Universe is winning.", Author: "Rick Cook"},
	{Text: "Optimize for programmer happiness.", Author: "David Heinemeier Hansson"},
	{Text: "The key is deliberate practice: not just doing it again and again, but challenging yourself with a task that is just beyond your current ability.", Author: "Peter Norvig"},
	{Text: "Design is not just what it looks like and feels like. Design is how it works.", Author: "Steve Jobs"},
	{Text: "Our civilization runs on software.", Author: "Bjarne Stroustrup"},
	{Text: "Walking on water and developing software from a specification are easy if both are frozen.", Author: "Edward V. Berard"},
	{Text: "First, solve the problem. Then, write the code.", Author: "John Johnson"},
	{Text: "The programmer, like the poet, works only slightly removed from pure thought-stuff. He builds his castles in the air, from air, creating by exertion of the imagination.", Author: "Fred Brooks"},
	{Text: "The hardest single part of building a software system is deciding precisely what to build.", Author: "Fred Brooks"},
	{Text: "How does a project get to be a year late? One day at a time.", Author: "Fred Brooks"},
	{Text: "Even the best planning is not so omniscient as to get it right the first time.", Author: "Fred Brooks"},
	{Text: "The best programs are written so that computing machines can perform them quickly and so that human beings can understand them clearly.", Author: "Donald Knuth"},
	{Text: "Science is what we understand well enough to explain to a computer. Art is everything else we do.", Author: "Donald Knuth"},
	{Text: "An algorithm must be seen to be believed.", Author: "Donald Knuth"},
	{Text: "Computers are good at following instructions, but not at reading your mind.", Author: "Donald Knuth"},
	{Text: "The art of programming is the art of organizing complexity, of mastering multitude and avoiding its bastard chaos as effectively as possible.", Author: "Edsger W. Dijkstra"},
	{Text: "The computing scientist's main challenge is not to get confused by the complexities of his own making.", Author: "Edsger W. Dijkstra"},
	{Text: "Elegance is not a dispensable luxury but a quality that decides between success and failure.", Author: "Edsger W. Dijkstra"},
	{Text: "The tools we use have a profound (and devious!) influence on our thinking habits, and, therefore, on our thinking abilities.", Author: "Edsger W. Dijkstra"},
	{Text: "Computer science is no more about computers than astronomy is about telescopes.", Author: "Edsger W. Dijkstra"},
	{Text: "Every program is a part of some other program and rarely fits.", Author: "Alan Perlis"},
	{Text: "One man's constant is another man's variable.", Author: "Alan Perlis"},
	{Text: "If you have a procedure with ten parameters, you probably missed some.", Author: "Alan Perlis"},
	{Text: "Recursion is the root of computation since it trades description for time.", Author: "Alan Perlis"},
	{Text: "Everything should be built top-down, except the first time.", Author: "Alan Perlis"},
	{Text: "Programmers are not to be measured by their ingenuity and their logic but by the completeness of their case analysis.", Author: "Alan Perlis"},
	{Text: "I think that it's extraordinarily important that we in computer science keep fun in computing.", Author: "Alan Perlis"},
	{Text: "The purpose of computing is insight, not numbers.", Author: "Richard Hamming"},
	{Text: "If you don't work on important problems, you can't expect to do important work.", Author: "Richard Hamming"},
	{Text: "Caches are bugs waiting to happen.", Author: "Rob Pike"},
	{Text: "Errors are values.", Author: "Rob Pike"},
	{Text: "Make the zero value useful.", Author: "Rob Pike"},
	{Text: "Gofmt's style is no one's favorite, yet gofmt is everyone's favorite.", Author: "Rob Pike"},
	{Text: "Design the architecture, name the components, document the details.", Author: "Rob Pike"},
	{Text: "Unix was not designed to stop you from doing stupid things, because that would also stop you from doing clever things.", Author: "Doug Gwyn"},
	{Text: "Unix is user-friendly. It's just selective about who its friends are.", Author: "Hacker proverb"},
	{Text: "The Linux philosophy is 'Laugh in the face of danger.' Oops. Wrong one. 'Do it yourself.' Yes, that's it.", Author: "Linus Torvalds"},
	{Text: "Intelligence is the ability to avoid doing work, yet getting the work done.", Author: "Linus Torvalds"},
	{Text: "Theory and practice sometimes clash. And when that happens, theory loses. Every single time.", Author: "Linus Torvalds"},
	{Text: "In real open source, you have the right to control your own destiny.", Author: "Linus Torvalds"},
	{Text: "Any program is only as good as it is useful.", Author: "Linus Torvalds"},
	{Text: "If you want to travel around the world and be invited to speak at a lot of different places, just write a Unix operating system.", Author: "Linus Torvalds"},
	{Text: "Sharing knowledge is the most fundamental act of friendship. Because it is a way you can give something without losing something.", Author: "Richard Stallman"},
	{Text: "Copying all or parts of a program is as natural to a programmer as breathing, and as productive. It ought to be as free.", Author: "Richard Stallman"},
	{Text: "The Internet interprets censorship as damage and routes around it.", Author: "John Gilmore"},
	{Text: "Code is law.", Author: "Lawrence Lessig"},
	{Text: "The best way to get the right answer on the Internet is not to ask a question; it's to post the wrong answer.", Author: "Cunningham's Law"},
	{Text: "What's the simplest thing that could possibly work?", Author: "Ward Cunningham"},
	{Text: "Always implement things when you actually need them, never when you just foresee that you need them.", Author: "Ron Jeffries"},
	{Text: "Documentation is a love letter that you write to your future self.", Author: "Damian Conway"},
	{Text: "Code without tests is broken by design.", Author: "Jacob Kaplan-Moss"},
	{Text: "Any code of your own that you haven't looked at for six or more months might as well have been written by someone else.", Author: "Eagleson's Law"},
	{Text: "There is no code so big, twisted, or complex that maintenance can't make it worse.", Author: "Gerald Weinberg"},
	{Text: "Software is like entropy: it is difficult to grasp, weighs nothing, and obeys the Second Law of Thermodynamics; i.e., it always increases.", Author: "Norman Augustine"},
	{Text: "Software is a gas; it expands to fill its container.", Author: "Nathan Myhrvold"},
	{Text: "We build our computer systems the way we build our cities: over time, without a plan, on top of ruins.", Author: "Ellen Ullman"},
	{Text: "Abstraction is selective ignorance.", Author: "Andrew Koenig"},
	{Text: "Threads are for people who can't program state machines.", Author: "Alan Cox"},
	{Text: "To iterate is human, to recurse divine.", Author: "L. Peter Deutsch"},
	{Text: "The good news about computers is that they do what you tell them to do. The bad news is that they do what you tell them to do.", Author: "Ted Nelson"},
	{Text: "Computers are like Old Testament gods; lots of rules and no mercy.", Author: "Joseph Campbell"},
	{Text: "Never trust a computer you can't throw out a window.", Author: "Steve Wozniak"},
	{Text: "Security is a process, not a product.", Author: "Bruce Schneier"},
	{Text: "Complexity is the worst enemy of security.", Author: "Bruce Schneier"},
	{Text: "Anyone, from the most clueless amateur to the best cryptographer, can create an algorithm that he himself can't break.", Author: "Bruce Schneier"},
	{Text: "The enemy knows the system.", Author: "Claude Shannon"},
	{Text: "Programming isn't about what you know; it's about what you can figure out.", Author: "Chris Pine"},
	{Text: "Every great developer you know got there by solving problems they were unqualified to solve until they actually did it.", Author: "Patrick McKenzie"},
	{Text: "The most disastrous thing that you can ever learn is your first programming language.", Author: "Alan Kay"},
	{Text: "People who are really serious about software should make their own hardware.", Author: "Alan Kay"},
	{Text: "A change in perspective is worth 80 IQ points.", Author: "Alan Kay"},
	{Text: "Technology is anything that wasn't around when you were born.", Author: "Alan Kay"},
	{Text: "The most important single aspect of software development is to be clear about what you are trying to build.", Author: "Bjarne Stroustrup"},
	{Text: "The most fundamental problem in software development is complexity. There is only one basic way of dealing with complexity: divide and conquer.", Author: "Bjarne Stroustrup"},
	{Text: "Design and programming are human activities; forget that and all is lost.", Author: "Bjarne Stroustrup"},
	{Text: "C makes it easy to shoot yourself in the foot; C++ makes it harder, but when you do it blows your whole leg off.", Author: "Bjarne Stroustrup"},
	{Text: "Programming is the art of doing one thing at a time.", Author: "Michael Feathers"},
	{Text: "If it hurts, do it more frequently, and bring the pain forward.", Author: "Jez Humble"},
	{Text: "Before software can be reusable it first has to be usable.", Author: "Ralph Johnson"},
	{Text: "The hardest part of design is keeping features out.", Author: "Donald Norman"},
	{Text: "A user interface is like a joke. If you have to explain it, it's not that good.", Author: "Martin LeBlanc"},
	{Text: "The best error message is the one that never shows up.", Author: "Thomas Fuchs"},
	{Text: "Without requirements or design, programming is the art of adding bugs to an empty text file.", Author: "Louis Srygley"},
	{Text: "The first step of any project is to grossly underestimate its complexity and difficulty.", Author: "Nicoll Hunt"},
	{Text: "The trick is to fix the problem you have, rather than the problem you want.", Author: "Bram Cohen"},
	{Text: "One of the best programming skills you can have is knowing when to walk away for a while.", Author: "Oscar Godson"},
	{Text: "Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday's code.", Author: "Dan Salomon"},
	{Text: "Hardware eventually fails. Software eventually works.", Author: "Michael Hartung"},
	{Text: "Software and cathedrals are much the same: first we build them, then we pray.", Author: "Samuel Redwine"},
	{Text: "If you automate a mess, you get an automated mess.", Author: "Rod Michael"},
	{Text: "Perl: the only language that looks the same before and after RSA encryption.", Author: "Keith Bostic"},
	{Text: "Java is to JavaScript what car is to carpet.", Author: "Chris Heilmann"},
	{Text: "Computers make very fast, very accurate mistakes.", Author: "Anonymous"},
	{Text: "The best thing about a boolean is even if you are wrong, you are only off by a bit.", Author: "Anonymous"},
	{Text: "There are 10 types of people in the world: those who understand binary, and those who don't.", Author: "Hacker proverb"},
	{Text: "It's not a bug, it's a feature.", Author: "Hacker proverb"},
	{Text: "Fast, good, cheap: pick any two.", Author: "Engineering proverb"},
	{Text: "Nothing is more permanent than a temporary solution.", Author: "Engineering proverb"},
	{Text: "Good judgment comes from experience, and experience comes from bad judgment.", Author: "Engineering proverb"},
	{Text: "The Analytical Engine has no pretensions whatever to originate anything. It can do whatever we know how to order it to perform.", Author: "Ada Lovelace"},
	{Text: "Machines take me by surprise with great frequency.", Author: "Alan Turing"},
	{Text: "One accurate measurement is worth a thousand expert opinions.", Author: "Grace Hopper"},
	{Text: "To me programming is more than an important practical art. It is also a gigantic undertaking in the foundations of knowledge.", Author: "Grace Hopper"},
	{Text: "Everyone in this country should learn how to program a computer, because it teaches you how to think.", Author: "Steve Jobs"},
	{Text: "The best programmers are not marginally better than merely good ones. They are an order-of-magnitude better.", Author: "Randall E. Stross"},
	{Text: "Software is eating the world.", Author: "Marc Andreessen"},
	{Text: "Any sufficiently advanced technology is indistinguishable from magic.", Author: "Arthur C. Clarke"},
}
