#!/usr/bin/env bash
# Generates Formula/fossc.rb for the Homebrew tap from a goreleaser
# checksums.txt, then pushes it to VanshSahay/homebrew-tap.
#
# Usage: build-formula.sh <version-without-v> <checksums.txt>
# Env:   TAP_GITHUB_TOKEN (required for push; omit to just print)
set -euo pipefail

version="${1:?version}"
checksums="${2:?checksums file}"
repo="VanshSahay/homebrew-tap"
base="https://github.com/VanshSahay/fossc/releases/download/v${version}"

sha() { awk -v f="$2" '$2 ~ f {print $1}' "$1"; }

darwin_arm64=$(sha "$checksums" "fossc_${version}_darwin_arm64.tar.gz$")
darwin_amd64=$(sha "$checksums" "fossc_${version}_darwin_amd64.tar.gz$")
linux_arm64=$(sha "$checksums" "fossc_${version}_linux_arm64.tar.gz$")
linux_amd64=$(sha "$checksums" "fossc_${version}_linux_amd64.tar.gz$")

formula=$(cat <<EOF
# Generated by scripts/build-formula.sh — do not edit by hand.
class Fossc < Formula
  desc "FOSS Club KIET operational handbook and gateway — terminal gazette"
  homepage "https://github.com/VanshSahay/fossc"
  version "${version}"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "${base}/fossc_${version}_darwin_arm64.tar.gz"
      sha256 "${darwin_arm64}"
    else
      url "${base}/fossc_${version}_darwin_amd64.tar.gz"
      sha256 "${darwin_amd64}"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "${base}/fossc_${version}_linux_arm64.tar.gz"
      sha256 "${linux_arm64}"
    else
      url "${base}/fossc_${version}_linux_amd64.tar.gz"
      sha256 "${linux_amd64}"
    end
  end

  def install
    bin.install "fossc"
    man1.install "fossc.1"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/fossc --version")
  end
end
EOF
)

echo "$formula"

# Without a token (snapshot/local runs) just print.
if [[ -z "${TAP_GITHUB_TOKEN:-}" ]]; then
  echo "TAP_GITHUB_TOKEN not set — formula not pushed." >&2
  exit 0
fi

for attempt in 1 2 3; do
  if gh api \
       --method PUT \
       "repos/${repo}/contents/Formula/fossc.rb" \
       -f message="fossc ${version}" \
       -f content="$(echo "$formula" | base64)" \
       -f sha="$(gh api "repos/${repo}/contents/Formula/fossc.rb" --jq .sha 2>/dev/null || true)" \
       --jq .commit.sha >/dev/null; then
    echo "Formula pushed to ${repo}." >&2
    exit 0
  fi
  sleep $((attempt * 5))
done
echo "Failed to push formula to ${repo}." >&2
exit 1
